### PR TITLE
feat: add support to deploy multiple apps in one command

### PR DESCRIPTION
**Pull request by ChrisPRobinson**
## What this PR does / why we need it
Adds support to be able to call install multiple apps at one time.

## Jira ID

[DT-2695]

## Notes for your reviewers
Attempted to add this functionality. Not doing all operations in parallel in the fastest way but waiting on the wait for pods at the end.

[DT-2695]: https://outreach-io.atlassian.net/browse/DT-2695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ChrisPRobinson** [comment]
DeployingMultipleAppsAtOneTime

**Comment by ChrisPRobinson** [comment]
Below is how it behaves and works

MultipleAppsDeploying

**Review by jaredallard — APPROVED** [review]

**Comment by jaredallard** [comment]
Didn't realize we had this when I made my PR :D

**Comment by ChrisPRobinson** [comment]
@jaredallard forgot about that PR, glad to help

**Pull request merged**
